In [2]:
import torch
import math

In [3]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros = torch.zeros(2,3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random1)

random4 = torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [7]:
some_constants = torch.tensor([[1,2],[3,4]])
print(some_constants)

some_integers = torch.tensor((1,2,3,4,5,6))
print(some_integers)

more_integers = torch.tensor(((2,4,6),[3,5,7]))
print(more_integers)

tensor([[1, 2],
        [3, 4]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[2, 4, 6],
        [3, 5, 7]])


In [8]:
a = torch.ones((2,3), dtype = torch.int16)
print(a)

b = torch.rand((2,3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [9]:
ones = torch.zeros(2,2) + 1
twos = torch.ones(2,2) * 2
threes = (torch.ones(2,2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
powers2 = twos ** torch.tensor([[1,2],[3,4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [3]:
a = torch.rand(2,3)
b = torch.rand(3,2)

print(a*b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

### Tensor Broadcasting

In [5]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)

print(rand)
print(doubled)

tensor([[0.8567, 0.2347, 0.2062, 0.3179],
        [0.6792, 0.8635, 0.5435, 0.8489]])
tensor([[1.7134, 0.4694, 0.4124, 0.6357],
        [1.3584, 1.7270, 1.0871, 1.6978]])


In [6]:
a = torch.ones(4,3,2)

b = a * torch.rand(3,2)

c = a * torch.rand(3,1)

d = a * torch.rand(1,2)

In [7]:
print(b)
print(c)
print(d)

tensor([[[0.2072, 0.1752],
         [0.3074, 0.6551],
         [0.0989, 0.8280]],

        [[0.2072, 0.1752],
         [0.3074, 0.6551],
         [0.0989, 0.8280]],

        [[0.2072, 0.1752],
         [0.3074, 0.6551],
         [0.0989, 0.8280]],

        [[0.2072, 0.1752],
         [0.3074, 0.6551],
         [0.0989, 0.8280]]])
tensor([[[0.8567, 0.8567],
         [0.0159, 0.0159],
         [0.6352, 0.6352]],

        [[0.8567, 0.8567],
         [0.0159, 0.0159],
         [0.6352, 0.6352]],

        [[0.8567, 0.8567],
         [0.0159, 0.0159],
         [0.6352, 0.6352]],

        [[0.8567, 0.8567],
         [0.0159, 0.0159],
         [0.6352, 0.6352]]])
tensor([[[0.8040, 0.5388],
         [0.8040, 0.5388],
         [0.8040, 0.5388]],

        [[0.8040, 0.5388],
         [0.8040, 0.5388],
         [0.8040, 0.5388]],

        [[0.8040, 0.5388],
         [0.8040, 0.5388],
         [0.8040, 0.5388]],

        [[0.8040, 0.5388],
         [0.8040, 0.5388],
         [0.8040, 0.5388]]])


### Others

In [9]:
# Common functions
a = torch.rand(2,4) * 2 -1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[ 0.1629,  0.1902, -0.2458,  0.3864],
        [-0.3793,  0.9265, -0.3867, -0.7026]])
tensor([[0.1629, 0.1902, 0.2458, 0.3864],
        [0.3793, 0.9265, 0.3867, 0.7026]])
tensor([[1., 1., -0., 1.],
        [-0., 1., -0., -0.]])
tensor([[ 0.,  0., -1.,  0.],
        [-1.,  0., -1., -1.]])
tensor([[ 0.1629,  0.1902, -0.2458,  0.3864],
        [-0.3793,  0.5000, -0.3867, -0.5000]])


In [12]:
angles = torch.tensor([0, math.pi/4, math.pi/2, 3* math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print(angles)
print(sines)
print(inverses)

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [13]:
b = torch.tensor([1,5,11])
c = torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

tensor([3, 2, 1])


In [14]:
d = torch.tensor([[1.,2.],[3.,4.]])
e = torch.ones(1,2)
print(torch.eq(d,e))

tensor([[ True, False],
        [False, False]])


In [16]:
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1,2,1,2,1,2])))

tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [17]:
v1 = torch.tensor([1.,0.,0.])
v2 = torch.tensor([0.,1.,0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.],[0.,3.]])

print(torch.cross(v2,v1))
print(m1)
m3 = torch.matmul(m1,m2)
print(m3)
print(torch.svd(m3))

tensor([ 0.,  0., -1.])
tensor([[0.1118, 0.7626],
        [0.4023, 0.2000]])
tensor([[0.3354, 2.2879],
        [1.2069, 0.6000]])
torch.return_types.svd(
U=tensor([[-0.9232, -0.3843],
        [-0.3843,  0.9232]]),
S=tensor([2.4672, 1.0376]),
V=tensor([[-0.3135,  0.9496],
        [-0.9496, -0.3135]]))


In [19]:
a = torch.tensor([0, math.pi/4, math.pi/2, 3* math.pi/4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi/4, math.pi/2, 3* math.pi/4])
print('\nb:')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [20]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.2577, 0.7679],
        [0.1754, 0.7394]])

After adding:
tensor([[1.2577, 1.7679],
        [1.1754, 1.7394]])
tensor([[1.2577, 1.7679],
        [1.1754, 1.7394]])
tensor([[0.2577, 0.7679],
        [0.1754, 0.7394]])

After multiplying
tensor([[0.0664, 0.5897],
        [0.0308, 0.5467]])
tensor([[0.0664, 0.5897],
        [0.0308, 0.5467]])


In [21]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)
old_id = id(c)

print(c)
d = torch.matmul(a,b, out=c)
print(c)

assert c is d
assert id(c) == old_id

torch.rand(2,2, out=c)
print(c)
assert id(c) == old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3048, 0.3620],
        [0.5641, 0.1755]])
tensor([[0.2548, 0.4543],
        [0.7937, 0.5769]])


In [22]:
a = torch.ones(2,2)
b = a.clone()

assert b is not a
print(torch.eq(a,b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [23]:
if torch.cuda.is_available():
    print("We have a GPU")
else:
    print("No GPU")

We have a GPU


In [24]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2,2, device='cuda')
    print(gpu_rand)
else:
    print("No GPU")

tensor([[0.4779, 0.1487],
        [0.2155, 0.8675]], device='cuda:0')


In [26]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2,2, device = my_device)
print(x)

Device: cuda
tensor([[0.9625, 0.3661],
        [0.7334, 0.0705]], device='cuda:0')


In [27]:
y = torch.rand(2,2)
y = y.to(my_device)

In [28]:
x = torch.rand(2,2)
y = torch.rand(2,2, device='gpu')
z = x + y

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu

In [29]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [30]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.9872]]]]])


In [31]:
a = torch.rand(1,20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2,2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.0851, 0.2478, 0.5658, 0.4555, 0.5187, 0.4111, 0.0284, 0.5268, 0.1407,
         0.4657, 0.5530, 0.9280, 0.6236, 0.5601, 0.7731, 0.2245, 0.2487, 0.0698,
         0.3087, 0.8687]])
torch.Size([20])
tensor([0.0851, 0.2478, 0.5658, 0.4555, 0.5187, 0.4111, 0.0284, 0.5268, 0.1407,
        0.4657, 0.5530, 0.9280, 0.6236, 0.5601, 0.7731, 0.2245, 0.2487, 0.0698,
        0.3087, 0.8687])
torch.Size([2, 2])
torch.Size([2, 2])


In [32]:
import numpy as np

numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [33]:
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1220, 0.1056, 0.9174],
        [0.3648, 0.0864, 0.3546]])
[[0.12204474 0.10557806 0.9173783 ]
 [0.36484706 0.08637154 0.35460675]]


In [34]:
numpy_array[1,1] = 23
print(pytorch_tensor)

pytorch_rand[1,1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.12204474  0.10557806  0.9173783 ]
 [ 0.36484706 17.          0.35460675]]
